'on':
  - push
  - pull_request
  - workflow_dispatch
jobs:
  build:
    - name: Build firmware
      uses: zmkfirmware/zmk@v0.3.0
      with:
        archiveName: firmware.zip
      configPath: config
